image: golang:1.16

services:
  - docker:dind

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - go mod download

unit_tests:
  stage: test
  script:
    - make test
